server {
    listen 8080;
    
    # root를 밖으로 빼서 전역 적용
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 리액트 라우팅 404 방어
    error_page 404 /index.html;

    # 캐시 설정 (성능 최적화)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf|otf|ttc)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
